[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tce-modifier"
version = "0.0.1"
description = "Modifier to compute cluster counts using the tensor cluster expansion formulism"
keywords = ["ovito", "ovito-extension"]
authors = [{name = "Jacob Jeffries", email = "jwjeffr@clemson.edu"}]
maintainers = [{name = "Jacob Jeffries", email = "jwjeffr@clemson.edu"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ovito >= 3.9.1",
    "tce-lib @ git+https://github.com/MUEXLY/tce-lib.git@194f4e2",
    "multiset >= 3.0.0"
]

[project.urls]
repository = "https://github.com/jwjeffr/tce-modifier"

[project.entry-points.'OVITO.Modifier']
"Tensor Cluster Expansion Modifier" = "tce_modifier:TCEModifier"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore:module 'sre_parse' is deprecated:DeprecationWarning",
    "ignore:module 'sre_constants' is deprecated:DeprecationWarning",
]
