# Boilerplate code generated by OVITO Pro 3.15.5
from pathlib import Path

from ovito.io import *
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *
from ovito.vis import *
from ovito.qt_compat import QtCore
from tce_modifier import *


def main():

    images_dir = Path("images")
    images_dir.mkdir(exist_ok=True, parents=True)

    for tce_id in range(49):

        print(tce_id)

        # ==== Set up pipeline ==== #

        # Data import:
        pipeline = import_file('ws2.xyz')

        # Edit simulation cell:
        def modify_cell(frame: int, data: DataCollection):
            data.cell_.pbc = (False, False, False)
        pipeline.modifiers.append(modify_cell)

        # Radial distribution function (RDF):
        pipeline.modifiers.append(RadialDistributionFunctionModifier(
            cutoff = 6.0, 
            partial = True))

        # Tensor cluster expansion:
        pipeline.modifiers.append(TCEModifier(
            neighbor_cutoffs = [2.5, 3.25, 4.0, 4.5, 5.0, 5.5], 
            many_body_features = [[0, 0, 1], [1, 1, 1], [0, 1, 2], [1, 2, 2], [0, 0, 0, 0, 1, 1], [0, 0, 0, 1, 1, 1], [1, 1, 1, 1, 1, 5]], 
            neighbor_tolerance = 0.05, 
            visualize_cluster = tce_id, 
            cluster_bond_width = 0.3, 
            unwrap_cluster_bonds = True))

        # Expression selection:
        pipeline.modifiers.append(ExpressionSelectionModifier(
            expression = 'TCEClusterID!=5', 
            operate_on = 'bonds'))

        # Delete selected:
        pipeline.modifiers.append(DeleteSelectedModifier())

        # ======= Set up visual elements ======= #

        # Configure visual elements for pipeline
        try:
            data = pipeline.compute()
        except RuntimeError:
            continue
        data.particles.vis.scaling = 0.25
        data.particles.bonds.vis.width = 0.3

        cluster_type, = {label for label in data.attributes if f"(ID = {tce_id:0d})" in label}
        cluster_type = cluster_type.replace(f" (ID = {tce_id:0d})", "")
        composition, *neighbor_labels = cluster_type.split(" + ")
        unique_characters_in_composition = set(composition)
        for character in unique_characters_in_composition:
            if not character.isnumeric():
                continue
            if character == "1":
                to_replace = ""
            else:
                to_replace = rf"<sub>{character}</sub>"
            composition = composition.replace(character, to_replace)

        cluster_type = f"{composition} — {'+'.join(neighbor_labels)}"

        # Add pipelines to visualization scene
        pipeline.add_to_scene()

        # ========== Set up rendering ========== #

        # Viewport setup:
        viewport_layout = []

        # Viewport "Front":
        vp = Viewport()
        vp.type = Viewport.Type.Front
        vp.fov = 8.83143368394
        vp.camera_pos = [2.255647564295997, 0.0, 3.2114304305231145]
        vp.overlays.append(CoordinateTripodOverlay(
            size = 0.1, 
            offset_x = 0.049, 
            offset_y = -0.0233, 
            font_size = 0.3, 
            axis1_label = '[001]', 
            axis2_label = '[010]', 
            axis3_label = '[001]', 
            axis2_dir = [-0.5, 0.866, 0.0], 
            axis1_color = [0.0, 0.0, 0.0], 
            axis2_color = [0.0, 0.0, 0.0], 
            axis3_color = [0.0, 0.0, 0.0]))
        vp.overlays.append(TextLabelOverlay(
            alignment = QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop, 
            offset_y = 0.02, 
            font_size = 0.05, 
            text = cluster_type, 
            pipeline = pipeline, 
            text_color = [0.0, 0.0, 0.0])
        )
        viewport_layout.append((vp, [0.0, 0.0, 0.5, 1.0]))  # [left,top,width,height]

        # Viewport "Perspective":
        vp = Viewport()
        vp.type = Viewport.Type.Perspective
        vp.fov = 0.610865238198
        vp.camera_dir = [-0.708108229221723, 0.5669062737307359, -0.42095131845999484]
        vp.camera_pos = [19.85672141441333, -9.969362955755342, 12.803261361348182]
        vp.camera_up = [-0.3286127254944541, 0.26308494665471566, 0.9070832307383883]
        vp.overlays.append(CoordinateTripodOverlay(
            size = 0.1, 
            font_size = 0.3, 
            axis1_label = '[001]', 
            axis2_label = '[010]', 
            axis3_label = '[001]', 
            axis2_dir = [-0.5, 0.866, 0.0], 
            axis1_color = [0.0, 0.0, 0.0], 
            axis2_color = [0.0, 0.0, 0.0], 
            axis3_color = [0.0, 0.0, 0.0]))
        vp.overlays.append(ColorLegendOverlay(
            alignment = QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignBottom, 
            offset_x = -0.033, 
            offset_y = 0.0378, 
            legend_size = 0.275, 
            font_size = 0.35, 
            label_size = 0.5, 
            title = ' ', 
            pipeline = pipeline, 
            property = "particles/Particle Type", 
            border_enabled = True))
        viewport_layout.append((vp, [0.5, 0.0, 0.5, 1.0]))  # [left,top,width,height]

        # Rendering:
        vp.render_image(filename=str(images_dir / f'{tce_id}.png'), size=(1000, 500), layout=viewport_layout)
        pipeline.remove_from_scene()


if __name__ == "__main__":

    main()
